# syntax=docker/dockerfile:1

ARG NODE_VERSION=24.18.0

FROM node:${NODE_VERSION}

WORKDIR /website/frontend

RUN apt-get update && apt-get install -y nginx \
        wget \
        nano \
        dnsutils \
        net-tools \
        git \
        curl \
        cmake \
        unzip \
        build-essential \
        software-properties-common \
        zip \
        cron \
        gpg

RUN rm -f /etc/nginx/sites-enabled/default

ARG NEXT_PUBLIC_MOCK_DATA
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_MOCK_DATA=$NEXT_PUBLIC_MOCK_DATA
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# COPY . .
EXPOSE 80
EXPOSE 3000

CMD ["bash", "-c", "service nginx start && yarn dev"]
