user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##
        
    log_format json_format_log escape=json '{'
        # Basic request information
        '"timestamp":"$time_local",'
        '"client_ip":"$remote_addr",'
        '"real_ip":"$realip_remote_addr",'
        '"forwarded_for":"$http_x_forwarded_for",'
        '"remote_user":"$remote_user",'

        # Request details
        '"request":"$request",'
        '"request_method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"server_protocol":"$server_protocol",'
        '"args":"$args",'
        '"request_length":"$request_length",'

        # Response information
        '"status":"$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"bytes_sent":"$bytes_sent",'
        '"content_type":"$sent_http_content_type",'
        '"content_length":"$sent_http_content_length",'

        #cloudflare
        '"ip_client_country":"$http_cf_ipcountry",'
        '"ip_client_city":"$http_cf_ipcity",'
        '"ip_client_continent":"$http_cf_ipcontinent",'
        '"ip_longitude":"$http_cf_iplongitude",'
        '"ip_latitude":"$http_cf_iplatitude",'
        '"ip_client_region":"$http_cf_region",'
        '"ip_client_region_code":"$http_cf_region_code",'
        '"ip_client_metro_code":"$http_cf_metro_code",'
        '"ip_client_postal_code":"$http_cf_postal_code",'
        '"ip_client_timezone":"$http_cf_timezone",'

        # Performance metrics
        '"request_time":"$request_time",'

        # HTTP headers and referrer information
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent",'
        '"http_host":"$http_host",'

        # Server information
        '"server_name":"$server_name",'
        '"server_port":"$server_port",'
        '"connection_requests":"$connection_requests",'
        '"connection":"$connection",'

        # Host information
        '"hostname":"$hostname"'
    '}';

        access_log /var/log/nginx/access.log;

        gzip on;


        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}